acl SSL_ports port 443
acl CONNECT method CONNECT
acl approved dstdomain .usgs.gov
http_access deny !SSL_ports
http_access allow CONNECT approved
http_access deny all
http_port 3128
cache deny all
access_log stdio:/dev/stdout
